name: check with local registry

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
          
      # - name: Build Docker image and push
      #   run: |
      #    docker buildx build -o - . > my-app.tar
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          pull: true
          tags: localhost:5000/my-app:latest
          
      # Set up Docker Buildx
      - name: Set up Docker Buildx 2
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
          
      - name: Build and push 2
        uses: docker/build-push-action@v6
        with:
          push: true
          pull: true
          tags: localhost:5000/my-app:latest
      - name: Inspect
        run: |
          docker buildx imagetools inspect localhost:5000/my-app:latest
          
