name: check with local cache

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: my-app:latest
          outputs: type=docker,dest=/tmp/myimage.tar
          cache-to: type=local,dest=/tmp/local-cache,mode=max

      - name: Upload cache
        uses: actions/upload-artifact@v4
        with:
         name: local-cache
         path: /tmp/local-cache
          
      
  re-build-from-artifacts:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    needs: build-and-upload

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: network=host
       
    - name: Download Docker cache from artifact
      uses: actions/download-artifact@v4
      with:
        name: local-cache
        path: /tmp/local-cache
        
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Rebuild using local registry cache
      uses: docker/build-push-action@v6
      with:
        push: true
        pull: true
        tags: localhost:5000/my-app:latest
        cache-from: type=local,src=/tmp/local-cache
        
    - name: Check 
      run: |
        docker pull localhost:5000/my-app:latest
        docker image ls -a
